auto code-formatter

diff --git a/.github/workflows/pythonpackage.yml b/.github/workflows/pythonpackage.yml
--- a/.github/workflows/pythonpackage.yml
+++ b/.github/workflows/pythonpackage.yml
@@ -20,21 +20,13 @@ jobs:
           VALIDATE_ENV: true
 
   lint:
-    name: Run Pylint on code base
-    needs: super-lint
+    name: Style check
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout Code
-        uses: actions/checkout@v2
-      - name: Set up Python 3.8
-        uses: actions/setup-python@v1
-        with:
-          python-version: 3.8
-      - name: Install dependencies
+      - name: Install Black
+        run: pip3 install -r dev-requirements.txt
+      - name: Black pep8 style
         run: |
-          python -m pip install --upgrade pip
-          pip install -r requirements.txt
-      - name: Lint CLI with pylint
-        run: pylint cli/
-      - name: Lint GUI with pylint
-        run: pylint gui/
+          echo "\e[36mChecking Python code style.\e[0m" && \
+          black ./ --check --diff || \
+          ( echo "\e[33mRun \e[36mmake format-style-python\e[33m to fix style errors.\e[0m"; exit 1 )
